In [1]:
# Import basic libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import gzip

In [2]:
test_df = pd.DataFrame(pd.read_csv('../00_Resources/fake_or_real_news.csv'))
test_df = test_df.drop(columns=['Unnamed: 0'])
test_df = test_df.replace({'FAKE': 'False', 'REAL': 'True'})
test_df

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",False
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,False
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,True
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",False
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,True
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,True
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,False
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,False
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",True
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,True

In [3]:
with open('../00_Resources/true_fake.csv', 'rb') as fd:
    gzip_fd = gzip.GzipFile(fileobj=fd)
    df = pd.read_csv(gzip_fd)
df = df.drop(columns={'Unnamed: 0','subject','date'})
df = df.rename(columns={'category':'label'})
# df = df.append(test_df, ignore_index=True)
df = df.sample(frac=1).reset_index(drop=True)
# df = df.loc[df['label'] != 'unknown']
df

,title,text,label
0,SYRIA: British and American Presence Directly ...,US paratrooper on security duty during a miss...,False
1,Growing unease as India curbs the net to keep ...,MUMBAI (Reuters) - First he tried messaging fr...,True
2,Republican Kasich: Presidential contests will ...,WASHINGTON (Reuters) - Republican candidate Jo...,True
3,The Sad Truth About Liberal Logic In One Meme,The liberal logic of Bernie Sanders fans who ...,False
4,Republican Party chairman confident in Clevela...,WASHINGTON (Reuters) - Republican Party chief ...,True
...,...,...,...
44893,Trump Crumbles As His Own UN Ambassador Shuts...,One of the craziest things about Trump s Russi...,False
44894,Lindsey Graham Makes The Most Depressing Pred...,Lindsey Graham (R-SC) has been going through a...,False
44895,High-Profile Attorney To Represent Trump’s Al...,Donald J. Trump s rape trial will be held on D...,False
44896,China says 'significant progress' was made on ...,BEIJING (Reuters) - China said on Thursday tha...,True
44897,Trump says he wants provision to lower drug co...,"LOUISVILLE, Ky. (Reuters) - President Donald T...",True

In [4]:
df_url = pd.DataFrame(pd.read_csv('../00_Resources/fake_news_with_url.csv'))
df_url = df_url.rename(columns={'Headline':'title','Body':'text'})
df_url['label'] = df_url['Label'].replace({0: 'False', 1: 'True'})
df_url = df_url.drop(columns=['URLs','Label'])
df_url = df_url.dropna(how='any')
df_url

,title,text,label
0,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,True
1,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - “Last Flag Flying”, a comed...",True
2,Trump’s Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,True
3,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...,True
4,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",True
...,...,...,...
4003,CNN and Globalist Exposed - Steve Quayle and A...,"Vietnam Is in Great Danger, You Must Publish a...",False
4004,Trends to Watch,Trends to Watch\n% of readers think this story...,False
4005,Trump Jr. Is Soon To Give A 30-Minute Speech F...,Trump Jr. Is Soon To Give A 30-Minute Speech F...,False
4007,China to accept overseas trial data in bid to ...,SHANGHAI (Reuters) - China said it plans to ac...,True
4008,Vice President Mike Pence Leaves NFL Game Beca...,Vice President Mike Pence Leaves NFL Game Beca...,False

In [8]:
df1 = pd.DataFrame(pd.read_csv('../00_Resources/Fake-News/train.csv'))
df2 = pd.DataFrame(pd.read_csv('../00_Resources/Fake-News/test.csv'))
df3 = pd.DataFrame(pd.read_csv('../00_Resources/Fake-News/submit.csv'))

df4 = df1.append(df2, ignore_index=True)
df_merge = pd.merge(df3, df4, on='id')

df_merge['label'] = df_merge['label_x'].replace({0: 'False', 1: 'True'})
df_merge = df_merge.drop(columns=['id','label_x','author','label_y'])
df_merge = df_merge.dropna(how='any')

df_merge

,title,text,label
0,"Specter of Trump Loosens Tongues, if Not Purse...","PALO ALTO, Calif. — After years of scorning...",False
1,Russian warships ready to strike terrorists ne...,Russian warships ready to strike terrorists ne...,True
2,#NoDAPL: Native American Leaders Vow to Stay A...,Videos #NoDAPL: Native American Leaders Vow to...,False
3,"Tim Tebow Will Attempt Another Comeback, This ...","If at first you don’t succeed, try a different...",True
4,Keiser Report: Meme Wars (E995),42 mins ago 1 Views 0 Comments 0 Likes 'For th...,True
...,...,...,...
5195,The Bangladeshi Traffic Jam That Never Ends - ...,Of all the dysfunctions that plague the world’...,False
5196,John Kasich Signs One Abortion Bill in Ohio bu...,WASHINGTON — Gov. John Kasich of Ohio on Tu...,True
5197,"California Today: What, Exactly, Is in Your Su...",Good morning. (Want to get California Today by...,False
5198,300 US Marines To Be Deployed To Russian Borde...,« Previous - Next » 300 US Marines To Be Deplo...,True
5199,"Awkward Sex, Onscreen and Off - The New York T...",Perhaps you’ve seen the new TV series whose pi...,False

In [9]:
df2 = df.append(test_df, ignore_index=True)
df3 = df2.append(df_url, ignore_index=True)
df4 = df3.append(df_merge, ignore_index=True)

df5 = df4.sample(frac=1).reset_index(drop=True)

df5

,title,text,label
0,"Donald Trump, in Scotland, Calls ‘Brexit’ Resu...","AYRSHIRE, Scotland — Donald J. Trump arrive...",False
1,‘Pay Bribes Here’ Projected On Trump Hotel,"Last night, Trump International Hotel in Washi...",False
2,UPDATE: BUSTED By The Secret Service…CNN’s Apr...,The Secret Service pushed back on a CNN report...,False
3,Commentary: Manic or evasive - these veep guys...,After going through a week reminiscent of Napo...,True
4,Judge Orders Trump To Court In Early January;...,One of Donald Trump s main tools as a business...,False
...,...,...,...
60287,"Chinese state media cheer Xi-Trump meeting, sa...",SHANGHAI/BEIJING (Reuters) - Chinese state med...,True
60288,China says has made best effort on North Korea...,BEIJING (Reuters) - A senior Chinese diplomat ...,True
60289,"Trump Team Didn’t Just Collude with Israel, Ku...",Patrick Henningsen 21st Century WireMuch was m...,False
60290,The Daily Caller Edits Woman’s Tragic Pregnan...,The Daily Caller is disgusting. Any media outl...,False
60291,Germany detains six Syrian suspected of planni...,BERLIN (Reuters) - German police on Tuesday de...,True

In [11]:
df5.to_csv('../00_Resources/all_merged_datasets.csv', compression='gzip')